import { cookiesManagement } from "../Logical/CookiesManagement";

const englishObject = {
    languajeElectorTag: "Languaje"
    ,loading: "Loading"
    ,enterYourMessageHere: "Enter your message here"
    ,addAccount: "Create Account"
    ,login: "Log In"
    ,donatives: "Make your donatives here"
    ,close: "Close"
    ,slogan: "This app was made to help persons and the medical assistance to cure them."
    ,or: "Or"
    ,password: "Password"
    ,profile: "Profile"
    ,authenticate: "Authenticate"
    ,create: "Create"
    ,client: "Client"
    ,channel: "Channel"
    ,company: "Company"
    ,edit: "Edit"
    ,email: "Email"
    ,choose: "Choose"
    ,deleteMessagePrompt: "Are you sure you want to delete this message?"
    ,deletedMessage: "Message has been deleted"
    ,home:"Home"
    ,thereAreNOElementsToShow: "There are no elements to show"
    ,servicesAndProducts: "Services and Products"
    ,more: "More about this chat"
    ,gettingMessagesFromServer : "Getting messages from server"
    ,delete: "Delete"
    ,back: "Back"
    ,requiredFields: "Required fields"
    ,recipes: "Recipes"
    ,recipe: "Recipe"
    ,role: "Role"
    ,phone: "Phone number"
    ,fill: "Fill"
    ,view: "View"
    ,add: "Add"
    ,cookiesMessage: "Please accept cookies (vegan please)."
    ,please: "Please"
    ,accept: "Accept"
    ,modify: "Modify"
    ,my: "My"
    ,moreAboutChat: "More options"
    ,name: "Name"
    ,product: "Product"
    ,products: "Products"
    ,preparation: "Preparation"
    ,description: "Description"
    ,nutrients: "Nutrients"
    ,getMessages: "Get Messages Update"
    ,go: "Go"
    ,message: "Message"
    ,isEmpty: "is empty"
    ,sendingMessage: "Sending message"
    ,sentMessage: "Message sent"
    ,save: "Send"
    ,session: "Session"
    ,search: "Search"
    ,scripts: "Scripts"
    ,steps: "Steps"
    ,update: "Update"
    ,verify: "Verify"
    ,example: "Example"
    ,enterChatId: "Enter chat ID"
    ,promptDeleteSubscription: "Do you want to delete this subcription?"
    ,subscriptions: "Subscriptions"
    ,scanThisQRCodeW: "Scan this qr code with your phone"
    ,shareThisQRCodeW: "Scan or share this qr code with your phone"
    ,youHaveSubscribed: "You have subscribed to this Chat"
    ,subscribeThisChat: "Subscribe to this Chat"
};

const spanishObject = {
    languajeElectorTag: "Lenguaje"
    ,enterYourMessageHere: "Ingrese aquí su mensaje"
    ,loading: "Cargando"
    ,addAccount: "Crear cuenta"
    ,login: "Acceder"
    ,slogan: "Esta aplicación se realizó para ayudar personas y equipo médico a guiarles en la curación."
    ,add: "Agregar"
    ,or: "Ó"
    ,password: "Contraseña"
    ,profile: "Perfil"
    ,authenticate: "Authenticarse"
    ,create: "Crear"
    ,client: "Cliente"
    ,close: "Cerrar"
    ,channel: "Canal ó Channel"
    ,company: "Compañía"
    ,edit: "Editar"
    ,email: "Email o correo electrónico"
    ,please: "Por favor"
    ,choose: "Elegir"
    ,deleteMessagePrompt: "¿Desea borrar el mensaje?"
    ,deletedMessage: "El mensaje ha sido borrado"
    ,save: "Enviar"
    ,donatives: "Haga sus donaciones aquí"
    ,home:"Inicio"
    ,thereAreNOElementsToShow: "No hay objeto que enseñar"
    ,gettingMessagesFromServer : "Obteniendo mensajes"
    ,delete: "Eliminar"
    ,back: "Volver"
    ,preparation: "Preparación"
    ,requiredFields: "Campos requeridos"
    ,servicesAndProducts: "Servicios y Productos"
    ,recipes: "Recetas"
    ,recipe: "Receta"
    ,role: "Rol"
    ,products: "Productos"
    ,phone: "Teléfono o número celular"
    ,fill: "Diligenciar"
    ,view: "Ver"
    ,cookiesMessage: "Por favor acepte el uso de cookies."
    ,accept: "Aceptar"
    ,getMessages: "Obtener mensajes"
    ,go: "Ir"
    ,message: "Mensaje"
    ,my: "Mi"
    ,modify: "Modificar"
    ,more: "Más sobre este chat"
    ,moreAboutChat: "Más opciones"
    ,name: "Nombre"
    ,product: "Producto"
    ,description: "Descripción"
    ,nutrients: "Nutrientes"
    ,isEmpty: "está vacío"
    ,scripts: "Guión"
    ,steps: "Pasos"
    ,search: "Buscar"
    ,sendingMessage: "Mensaje en proceso"
    ,sentMessage: "Mensaje se envío"
    ,session: "Sesión"
    ,update: "Actualizar"
    ,verify: "Verificar"
    ,example: "Ejemplo"
    ,enterChatId: "Introducir chat ID"
    ,promptDeleteSubscription: "¿Desea borrar esta subcripción?"
    ,subscriptions: "Suscripciones"
    ,scanThisQRCodeW: "Escanee este código QR con su celular"
    ,shareThisQRCodeW: "Escanee o comparta este código QR con su celular"
    ,youHaveSubscribed: "Te has suscrito a este Chat"
    ,subscribeThisChat: "Suscribirse a este Chat"
};

const frenchObject = {
    languajeElectorTag: "Langue"
    ,enterYourMessageHere: "Entrez votre message ici"
    ,loading: "Chargement"
    ,addAccount: "Créer compte"
    ,login: "Connexion"
    ,close: "Fermer"
    ,slogan: "Cette app a été crée par aideer les parsons et le equipe de médecints dans la soin."
    ,add: "Ajouter"
    ,or: "Ou"
    ,profile: "Profil"
    ,password: "Le Mot de passe"
    ,authenticate: "Authentifier"
    ,create: "Crée"
    ,servicesAndProducts: "Services et Produits"
    ,client: "Client"
    ,please: "S'il te plaît"
    ,channel: "Channel"
    ,company: "Compagnie"
    ,deleteMessagePrompt: "Êtes-vous sûr de vouloir supprimer ce message ?"
    ,deletedMessage: "Le message a été supprimé"
    ,donatives: "Faites votre don ici"
    ,more: "Plus sur ce chat"
    ,home:"Début"
    ,edit: "Éditer"
    ,email: "Email"
    ,choose: "Choisir"
    ,save: "Envoyer"
    ,thereAreNOElementsToShow: "Il n'y a aucun élément à afficher"
    ,delete: "Supprimer"
    ,back: "Retourner"
    ,requiredFields: "Champes requeris"
    ,recipes: "Recettes"
    ,recipe: "Recette"
    ,role: "Rôle"
    ,preparation: "Préparation"
    ,phone: "Téléphone"
    ,fill: "Remplir"
    ,modify: "Édite"
    ,my: "Mon"
    ,name: "Nom"
    ,view: "Voir"
    ,product: "Produit"
    ,products: "Produits"
    ,description: "Description"
    ,nutrients: "Nutriments"
    ,cookiesMessage: "S'il vous plaît"
    ,accept: "Accepter"
    ,getMessages: "Obtenir la messagerie"
    ,gettingMessagesFromServer : "Obtenir la messagerie"
    ,go: "Aller"
    ,moreAboutChat: "Plus d'options"
    ,message: "Message"
    ,isEmpty: "est vide"
    ,sendingMessage: "Message en envoi"
    ,sentMessage: "Message envoyé"
    ,session: "Session"
    ,scripts: "Instructions"
    ,search: "Chercher"
    ,steps: "Mesures"
    ,update: "Mettre à jour"
    ,verify: "Vérifier"
    ,example: "Exemple"
    ,enterChatId: "Entre chat ID"
    ,promptDeleteSubscription: "Voulez-vous supprimer cet abonnement?"
    ,subscriptions: "Abonnements"
    ,scanThisQRCodeW: "Scannez ce code QR avec votre téléphone portable"
    ,shareThisQRCodeW: "Scannez ou partagez ce code QR avec votre téléphone portable"
    ,youHaveSubscribed: "Vous vous êtes abonné à ce Chat"
    ,subscribeThisChat: "Abonnez-vous à ce chat"
};

//check if a method has or does
//mehtod: check if cookie has value
export const GetLanguaje = () => {
    const cookieToken = cookiesManagement.getCookie("languaje");
    
    //https://stackoverflow.com/questions/154059/how-do-i-check-for-an-empty-undefined-null-string-in-javascript
    return !cookieToken ? "english" : cookieToken.toString();
};

export const setLanguajeCookie = (token, datefinish) => {
    const cookie = `languaje=${token};expires=${datefinish}`;

    document.cookie = cookie;
};


export const langReference = (languaje) => {
    if (languaje === "english")
        return englishObject;

    if (languaje === "spanish")
        return spanishObject;

    if (languaje === "french")
        return frenchObject;

    //default
    return englishObject;
};


